// <auto-generated />
using System;
using GazeteDagitim.Web.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GazeteDagitim.Web.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260730224121_AddPaymentPeriodCollectionSchedule")]
    partial class AddPaymentPeriodCollectionSchedule
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.18")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GazeteDagitim.Web.Models.Entities.CashHandover", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<DateTimeOffset?>("DeliveredAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<decimal>("Total")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("Date")
                        .IsUnique()
                        .HasDatabaseName("UX_CashHandovers_Date");

                    b.HasIndex("Status", "Date")
                        .HasDatabaseName("IX_CashHandovers_Status_Date");

                    b.ToTable("CashHandovers", null, t =>
                        {
                            t.HasCheckConstraint("CK_CashHandovers_DeliveredAt", "([Status] = 0 AND [DeliveredAt] IS NULL) OR ([Status] = 1 AND [DeliveredAt] IS NOT NULL)");

                            t.HasCheckConstraint("CK_CashHandovers_Status", "[Status] BETWEEN 0 AND 1");

                            t.HasCheckConstraint("CK_CashHandovers_Total", "[Total] >= 0");
                        });
                });

            modelBuilder.Entity("GazeteDagitim.Web.Models.Entities.CashHandoverItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("CashHandoverId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("SubscriberName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("CashHandoverId");

                    b.ToTable("CashHandoverItems", null, t =>
                        {
                            t.HasCheckConstraint("CK_CashHandoverItems_Amount", "[Amount] >= 0");
                        });
                });

            modelBuilder.Entity("GazeteDagitim.Web.Models.Entities.CompanySettings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int?>("FeaturedDistributorId")
                        .HasColumnType("int");

                    b.Property<string>("LogoDataUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SingletonKey")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)")
                        .HasDefaultValue("company");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("FeaturedDistributorId");

                    b.HasIndex("SingletonKey")
                        .IsUnique()
                        .HasDatabaseName("UX_CompanySettings_SingletonKey");

                    b.ToTable("CompanySettings", null, t =>
                        {
                            t.HasCheckConstraint("CK_CompanySettings_LogoLength", "[LogoDataUrl] IS NULL OR LEN([LogoDataUrl]) <= 2796227");

                            t.HasCheckConstraint("CK_CompanySettings_SingletonKey", "[SingletonKey] = N'company'");
                        });
                });

            modelBuilder.Entity("GazeteDagitim.Web.Models.Entities.Delivery", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<int>("Day")
                        .HasColumnType("int");

                    b.Property<int>("DistributorId")
                        .HasColumnType("int");

                    b.Property<int>("NewspaperCount")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("Date", "Status")
                        .HasDatabaseName("IX_Deliveries_Date_Status");

                    b.HasIndex("DistributorId", "Date")
                        .IsUnique()
                        .HasDatabaseName("UX_Deliveries_Distributor_Date");

                    b.ToTable("Deliveries", null, t =>
                        {
                            t.HasCheckConstraint("CK_Deliveries_Amount", "[Amount] >= 0");

                            t.HasCheckConstraint("CK_Deliveries_Day", "[Day] BETWEEN 0 AND 6");

                            t.HasCheckConstraint("CK_Deliveries_NewspaperCount", "[NewspaperCount] >= 0");

                            t.HasCheckConstraint("CK_Deliveries_Status", "[Status] BETWEEN 0 AND 2");
                        });
                });

            modelBuilder.Entity("GazeteDagitim.Web.Models.Entities.Distributor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<decimal>("NewspaperPrice")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasDefaultValue(5m);

                    b.Property<int>("PaymentType")
                        .HasColumnType("int");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("ProfileImageDataUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("Zone")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IsActive", "Name")
                        .HasDatabaseName("IX_Distributors_Active_Name");

                    b.ToTable("Distributors", null, t =>
                        {
                            t.HasCheckConstraint("CK_Distributors_NewspaperPrice", "[NewspaperPrice] >= 0");

                            t.HasCheckConstraint("CK_Distributors_PaymentType", "[PaymentType] BETWEEN 0 AND 2");

                            t.HasCheckConstraint("CK_Distributors_ProfileImageLength", "[ProfileImageDataUrl] IS NULL OR LEN([ProfileImageDataUrl]) <= 2796227");

                            t.HasCheckConstraint("CK_Distributors_Zone", "[Zone] IN (1, 2)");
                        });
                });

            modelBuilder.Entity("GazeteDagitim.Web.Models.Entities.DistributorDistributionDay", b =>
                {
                    b.Property<int>("DistributorId")
                        .HasColumnType("int");

                    b.Property<int>("Day")
                        .HasColumnType("int");

                    b.HasKey("DistributorId", "Day");

                    b.ToTable("DistributorDistributionDays", null, t =>
                        {
                            t.HasCheckConstraint("CK_DistributorDistributionDays_Day", "[Day] BETWEEN 0 AND 6");
                        });
                });

            modelBuilder.Entity("GazeteDagitim.Web.Models.Entities.DistributorMonthlyPaymentDay", b =>
                {
                    b.Property<int>("DistributorId")
                        .HasColumnType("int");

                    b.Property<int>("DayOfMonth")
                        .HasColumnType("int");

                    b.HasKey("DistributorId", "DayOfMonth");

                    b.ToTable("DistributorMonthlyPaymentDays", null, t =>
                        {
                            t.HasCheckConstraint("CK_DistributorMonthlyPaymentDays_DayOfMonth", "[DayOfMonth] BETWEEN 1 AND 31");
                        });
                });

            modelBuilder.Entity("GazeteDagitim.Web.Models.Entities.DistributorWeeklyPaymentDay", b =>
                {
                    b.Property<int>("DistributorId")
                        .HasColumnType("int");

                    b.Property<int>("Day")
                        .HasColumnType("int");

                    b.HasKey("DistributorId", "Day");

                    b.ToTable("DistributorWeeklyPaymentDays", null, t =>
                        {
                            t.HasCheckConstraint("CK_DistributorWeeklyPaymentDays_Day", "[Day] BETWEEN 0 AND 6");
                        });
                });

            modelBuilder.Entity("GazeteDagitim.Web.Models.Entities.Payment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("DistributorId")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("PaidAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("PaymentType")
                        .HasColumnType("int");

                    b.Property<DateOnly>("PeriodEnd")
                        .HasColumnType("date");

                    b.Property<DateOnly>("PeriodStart")
                        .HasColumnType("date");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("Date", "Status")
                        .HasDatabaseName("IX_Payments_Date_Status");

                    b.HasIndex("DistributorId", "PaymentType", "PeriodEnd")
                        .IsDescending(false, false, true)
                        .HasDatabaseName("IX_Payments_Distributor_Type_PeriodEnd");

                    b.HasIndex("DistributorId", "PaymentType", "PeriodStart", "PeriodEnd")
                        .IsUnique()
                        .HasDatabaseName("UX_Payments_Distributor_Type_Period");

                    b.ToTable("Payments", null, t =>
                        {
                            t.HasCheckConstraint("CK_Payments_Amount", "[Amount] >= 0");

                            t.HasCheckConstraint("CK_Payments_PaidAt", "([Status] = 0 AND [PaidAt] IS NULL) OR ([Status] = 1 AND [PaidAt] IS NOT NULL)");

                            t.HasCheckConstraint("CK_Payments_Period", "[PeriodEnd] >= [PeriodStart]");

                            t.HasCheckConstraint("CK_Payments_Status", "[Status] BETWEEN 0 AND 1");

                            t.HasCheckConstraint("CK_Payments_Type", "[PaymentType] BETWEEN 0 AND 2");
                        });
                });

            modelBuilder.Entity("GazeteDagitim.Web.Models.Entities.PaymentPeriod", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("CollectionAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("CollectionDayOfMonth")
                        .HasColumnType("int");

                    b.Property<TimeOnly?>("CollectionTime")
                        .HasColumnType("time(0)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("DayCount")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)")
                        .UseCollation("Turkish_CI_AS");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("UX_PaymentPeriods_Name");

                    b.HasIndex("IsActive", "Name")
                        .HasDatabaseName("IX_PaymentPeriods_Active_Name");

                    b.ToTable("PaymentPeriods", null, t =>
                        {
                            t.HasCheckConstraint("CK_PaymentPeriods_CollectionDay", "[CollectionDayOfMonth] IS NULL OR [CollectionDayOfMonth] BETWEEN 1 AND 31");

                            t.HasCheckConstraint("CK_PaymentPeriods_CollectionSchedule", "([CollectionDayOfMonth] IS NULL AND [CollectionTime] IS NULL AND [CollectionAmount] IS NULL) OR ([CollectionDayOfMonth] IS NOT NULL AND [CollectionTime] IS NOT NULL AND [CollectionAmount] > 0)");

                            t.HasCheckConstraint("CK_PaymentPeriods_DayCount", "[DayCount] BETWEEN 1 AND 365");
                        });
                });

            modelBuilder.Entity("GazeteDagitim.Web.Models.Entities.Subscriber", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int?>("DistributorId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<decimal?>("Latitude")
                        .HasPrecision(9, 6)
                        .HasColumnType("decimal(9,6)");

                    b.Property<decimal?>("Longitude")
                        .HasPrecision(10, 6)
                        .HasColumnType("decimal(10,6)");

                    b.Property<decimal>("MonthlyFee")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar(160)");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int?>("PaymentPeriodId")
                        .HasColumnType("int");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("DistributorId")
                        .HasDatabaseName("IX_Subscribers_DistributorId");

                    b.HasIndex("Name")
                        .HasDatabaseName("IX_Subscribers_Name");

                    b.HasIndex("PaymentPeriodId")
                        .HasDatabaseName("IX_Subscribers_PaymentPeriodId");

                    b.HasIndex("IsActive", "Name")
                        .HasDatabaseName("IX_Subscribers_Active_Name");

                    b.ToTable("Subscribers", null, t =>
                        {
                            t.HasCheckConstraint("CK_Subscribers_Latitude", "[Latitude] IS NULL OR [Latitude] BETWEEN -90 AND 90");

                            t.HasCheckConstraint("CK_Subscribers_LocationPair", "([Latitude] IS NULL AND [Longitude] IS NULL) OR ([Latitude] IS NOT NULL AND [Longitude] IS NOT NULL)");

                            t.HasCheckConstraint("CK_Subscribers_Longitude", "[Longitude] IS NULL OR [Longitude] BETWEEN -180 AND 180");

                            t.HasCheckConstraint("CK_Subscribers_MonthlyFee", "[MonthlyFee] >= 0");
                        });
                });

            modelBuilder.Entity("GazeteDagitim.Web.Models.Entities.SubscriberDailyDelivery", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<int?>("DistributorId")
                        .HasColumnType("int");

                    b.Property<string>("DistributorName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<bool>("IsCollected")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDelivered")
                        .HasColumnType("bit");

                    b.Property<int>("NewspaperCount")
                        .HasColumnType("int");

                    b.Property<int>("PaymentMethod")
                        .HasColumnType("int");

                    b.Property<int>("SubscriberId")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("Date", "IsCollected")
                        .IsDescending(true, false)
                        .HasDatabaseName("IX_SubscriberDailyDeliveries_Date_Collected");

                    b.HasIndex("SubscriberId", "Date")
                        .IsUnique()
                        .HasDatabaseName("UX_SubscriberDailyDeliveries_Subscriber_Date");

                    b.HasIndex("DistributorId", "Date", "IsCollected", "PaymentMethod")
                        .IsDescending(false, true, false, false)
                        .HasDatabaseName("IX_SubscriberDailyDeliveries_Tracking");

                    b.ToTable("SubscriberDailyDeliveries", null, t =>
                        {
                            t.HasCheckConstraint("CK_SubscriberDailyDeliveries_Amount", "[Amount] >= 0 AND ([IsCollected] = 0 OR [Amount] > 0)");

                            t.HasCheckConstraint("CK_SubscriberDailyDeliveries_NewspaperCount", "[NewspaperCount] IN (1, 2)");

                            t.HasCheckConstraint("CK_SubscriberDailyDeliveries_PaymentMethod", "[PaymentMethod] BETWEEN 0 AND 2");
                        });
                });

            modelBuilder.Entity("GazeteDagitim.Web.Models.Entities.SubscriberDailyDeliveryCoveredDate", b =>
                {
                    b.Property<int>("SubscriberDailyDeliveryId")
                        .HasColumnType("int");

                    b.Property<DateOnly>("CoveredDate")
                        .HasColumnType("date");

                    b.HasKey("SubscriberDailyDeliveryId", "CoveredDate");

                    b.ToTable("SubscriberDailyDeliveryCoveredDates", (string)null);
                });

            modelBuilder.Entity("GazeteDagitim.Web.Models.Entities.SubscriberPublicationDay", b =>
                {
                    b.Property<int>("SubscriberId")
                        .HasColumnType("int");

                    b.Property<int>("Day")
                        .HasColumnType("int");

                    b.HasKey("SubscriberId", "Day");

                    b.ToTable("SubscriberPublicationDays", null, t =>
                        {
                            t.HasCheckConstraint("CK_SubscriberPublicationDays_Day", "[Day] BETWEEN 0 AND 7");
                        });
                });

            modelBuilder.Entity("GazeteDagitim.Web.Models.Entities.CashHandoverItem", b =>
                {
                    b.HasOne("GazeteDagitim.Web.Models.Entities.CashHandover", "CashHandover")
                        .WithMany("Items")
                        .HasForeignKey("CashHandoverId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CashHandover");
                });

            modelBuilder.Entity("GazeteDagitim.Web.Models.Entities.CompanySettings", b =>
                {
                    b.HasOne("GazeteDagitim.Web.Models.Entities.Distributor", "FeaturedDistributor")
                        .WithMany()
                        .HasForeignKey("FeaturedDistributorId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("FeaturedDistributor");
                });

            modelBuilder.Entity("GazeteDagitim.Web.Models.Entities.Delivery", b =>
                {
                    b.HasOne("GazeteDagitim.Web.Models.Entities.Distributor", "Distributor")
                        .WithMany("Deliveries")
                        .HasForeignKey("DistributorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Distributor");
                });

            modelBuilder.Entity("GazeteDagitim.Web.Models.Entities.DistributorDistributionDay", b =>
                {
                    b.HasOne("GazeteDagitim.Web.Models.Entities.Distributor", "Distributor")
                        .WithMany("DistributionDays")
                        .HasForeignKey("DistributorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Distributor");
                });

            modelBuilder.Entity("GazeteDagitim.Web.Models.Entities.DistributorMonthlyPaymentDay", b =>
                {
                    b.HasOne("GazeteDagitim.Web.Models.Entities.Distributor", "Distributor")
                        .WithMany("MonthlyPaymentDays")
                        .HasForeignKey("DistributorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Distributor");
                });

            modelBuilder.Entity("GazeteDagitim.Web.Models.Entities.DistributorWeeklyPaymentDay", b =>
                {
                    b.HasOne("GazeteDagitim.Web.Models.Entities.Distributor", "Distributor")
                        .WithMany("WeeklyPaymentDays")
                        .HasForeignKey("DistributorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Distributor");
                });

            modelBuilder.Entity("GazeteDagitim.Web.Models.Entities.Payment", b =>
                {
                    b.HasOne("GazeteDagitim.Web.Models.Entities.Distributor", "Distributor")
                        .WithMany("Payments")
                        .HasForeignKey("DistributorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Distributor");
                });

            modelBuilder.Entity("GazeteDagitim.Web.Models.Entities.Subscriber", b =>
                {
                    b.HasOne("GazeteDagitim.Web.Models.Entities.Distributor", "Distributor")
                        .WithMany("Subscribers")
                        .HasForeignKey("DistributorId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("GazeteDagitim.Web.Models.Entities.PaymentPeriod", "PaymentPeriod")
                        .WithMany("Subscribers")
                        .HasForeignKey("PaymentPeriodId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Distributor");

                    b.Navigation("PaymentPeriod");
                });

            modelBuilder.Entity("GazeteDagitim.Web.Models.Entities.SubscriberDailyDelivery", b =>
                {
                    b.HasOne("GazeteDagitim.Web.Models.Entities.Distributor", "Distributor")
                        .WithMany("SubscriberDailyDeliveries")
                        .HasForeignKey("DistributorId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("GazeteDagitim.Web.Models.Entities.Subscriber", "Subscriber")
                        .WithMany("DailyDeliveries")
                        .HasForeignKey("SubscriberId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Distributor");

                    b.Navigation("Subscriber");
                });

            modelBuilder.Entity("GazeteDagitim.Web.Models.Entities.SubscriberDailyDeliveryCoveredDate", b =>
                {
                    b.HasOne("GazeteDagitim.Web.Models.Entities.SubscriberDailyDelivery", "SubscriberDailyDelivery")
                        .WithMany("CoveredDates")
                        .HasForeignKey("SubscriberDailyDeliveryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SubscriberDailyDelivery");
                });

            modelBuilder.Entity("GazeteDagitim.Web.Models.Entities.SubscriberPublicationDay", b =>
                {
                    b.HasOne("GazeteDagitim.Web.Models.Entities.Subscriber", "Subscriber")
                        .WithMany("NewspaperDays")
                        .HasForeignKey("SubscriberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Subscriber");
                });

            modelBuilder.Entity("GazeteDagitim.Web.Models.Entities.CashHandover", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("GazeteDagitim.Web.Models.Entities.Distributor", b =>
                {
                    b.Navigation("Deliveries");

                    b.Navigation("DistributionDays");

                    b.Navigation("MonthlyPaymentDays");

                    b.Navigation("Payments");

                    b.Navigation("SubscriberDailyDeliveries");

                    b.Navigation("Subscribers");

                    b.Navigation("WeeklyPaymentDays");
                });

            modelBuilder.Entity("GazeteDagitim.Web.Models.Entities.PaymentPeriod", b =>
                {
                    b.Navigation("Subscribers");
                });

            modelBuilder.Entity("GazeteDagitim.Web.Models.Entities.Subscriber", b =>
                {
                    b.Navigation("DailyDeliveries");

                    b.Navigation("NewspaperDays");
                });

            modelBuilder.Entity("GazeteDagitim.Web.Models.Entities.SubscriberDailyDelivery", b =>
                {
                    b.Navigation("CoveredDates");
                });
#pragma warning restore 612, 618
        }
    }
}
